/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExchangeRouteImport } from './routes/exchange'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutusRouteImport } from './routes/aboutus'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamUuidRouteImport } from './routes/team.$uuid'
import { Route as JoinTokenRouteImport } from './routes/join.$token'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeRoute = ExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutusRoute = AboutusRouteImport.update({
  id: '/aboutus',
  path: '/aboutus',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamUuidRoute = TeamUuidRouteImport.update({
  id: '/$uuid',
  path: '/$uuid',
  getParentRoute: () => TeamRoute,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aboutus': typeof AboutusRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/exchange': typeof ExchangeRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/projects': typeof ProjectsRoute
  '/team': typeof TeamRouteWithChildren
  '/join/$token': typeof JoinTokenRoute
  '/team/$uuid': typeof TeamUuidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aboutus': typeof AboutusRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/exchange': typeof ExchangeRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/projects': typeof ProjectsRoute
  '/team': typeof TeamRouteWithChildren
  '/join/$token': typeof JoinTokenRoute
  '/team/$uuid': typeof TeamUuidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aboutus': typeof AboutusRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/exchange': typeof ExchangeRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/projects': typeof ProjectsRoute
  '/team': typeof TeamRouteWithChildren
  '/join/$token': typeof JoinTokenRoute
  '/team/$uuid': typeof TeamUuidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aboutus'
    | '/admin'
    | '/contact'
    | '/exchange'
    | '/login'
    | '/portal'
    | '/projects'
    | '/team'
    | '/join/$token'
    | '/team/$uuid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aboutus'
    | '/admin'
    | '/contact'
    | '/exchange'
    | '/login'
    | '/portal'
    | '/projects'
    | '/team'
    | '/join/$token'
    | '/team/$uuid'
  id:
    | '__root__'
    | '/'
    | '/aboutus'
    | '/admin'
    | '/contact'
    | '/exchange'
    | '/login'
    | '/portal'
    | '/projects'
    | '/team'
    | '/join/$token'
    | '/team/$uuid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutusRoute: typeof AboutusRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  ExchangeRoute: typeof ExchangeRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRoute
  ProjectsRoute: typeof ProjectsRoute
  TeamRoute: typeof TeamRouteWithChildren
  JoinTokenRoute: typeof JoinTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange': {
      id: '/exchange'
      path: '/exchange'
      fullPath: '/exchange'
      preLoaderRoute: typeof ExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aboutus': {
      id: '/aboutus'
      path: '/aboutus'
      fullPath: '/aboutus'
      preLoaderRoute: typeof AboutusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$uuid': {
      id: '/team/$uuid'
      path: '/$uuid'
      fullPath: '/team/$uuid'
      preLoaderRoute: typeof TeamUuidRouteImport
      parentRoute: typeof TeamRoute
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TeamRouteChildren {
  TeamUuidRoute: typeof TeamUuidRoute
}

const TeamRouteChildren: TeamRouteChildren = {
  TeamUuidRoute: TeamUuidRoute,
}

const TeamRouteWithChildren = TeamRoute._addFileChildren(TeamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutusRoute: AboutusRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  ExchangeRoute: ExchangeRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRoute,
  ProjectsRoute: ProjectsRoute,
  TeamRoute: TeamRouteWithChildren,
  JoinTokenRoute: JoinTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
