// GENERATED FILE — do not edit by hand.
//
// Country names are emitted from the runtime's ICU data (Intl.DisplayNames) and
// the code list is derived from the flag SVGs vendored in
// src/assets/flags/countries, so every entry here is guaranteed to have a flag
// to render. Regenerate with scripts/gen-exchange-data.mjs.
//
// Exchange destinations are stored on the member record as
// `exchangeCountry` (ISO 3166-1 alpha-2) plus, for Brazil, `exchangeState`
// (the two-letter UF). The public /exchange page reads them live from the API —
// there is no hand-maintained roster any more.

/** ISO 3166-1 alpha-2. Kept as a string so a new country never needs a code change. */
export type CountryCode = string;

export interface CountryMeta {
  code: CountryCode;
  name: { pt: string; en: string; fr: string };
}

/** The one country that also carries a state, for national mobility. */
export const BRAZIL: CountryCode = "BR";

export interface BrStateMeta {
  /** Two-letter UF. */
  code: string;
  name: string;
  /** IBGE macro-region, used to group the picker. */
  region: "Norte" | "Nordeste" | "Centro-Oeste" | "Sudeste" | "Sul";
}

export const COUNTRIES: Record<CountryCode, CountryMeta> = {
  AF: { code: "AF", name: { pt: "Afeganistão", en: "Afghanistan", fr: "Afghanistan" } },
  ZA: { code: "ZA", name: { pt: "África do Sul", en: "South Africa", fr: "Afrique du Sud" } },
  AL: { code: "AL", name: { pt: "Albânia", en: "Albania", fr: "Albanie" } },
  DE: { code: "DE", name: { pt: "Alemanha", en: "Germany", fr: "Allemagne" } },
  AD: { code: "AD", name: { pt: "Andorra", en: "Andorra", fr: "Andorre" } },
  AO: { code: "AO", name: { pt: "Angola", en: "Angola", fr: "Angola" } },
  AI: { code: "AI", name: { pt: "Anguila", en: "Anguilla", fr: "Anguilla" } },
  AQ: { code: "AQ", name: { pt: "Antártida", en: "Antarctica", fr: "Antarctique" } },
  AG: {
    code: "AG",
    name: { pt: "Antígua e Barbuda", en: "Antigua & Barbuda", fr: "Antigua-et-Barbuda" },
  },
  SA: { code: "SA", name: { pt: "Arábia Saudita", en: "Saudi Arabia", fr: "Arabie saoudite" } },
  DZ: { code: "DZ", name: { pt: "Argélia", en: "Algeria", fr: "Algérie" } },
  AR: { code: "AR", name: { pt: "Argentina", en: "Argentina", fr: "Argentine" } },
  AM: { code: "AM", name: { pt: "Armênia", en: "Armenia", fr: "Arménie" } },
  AW: { code: "AW", name: { pt: "Aruba", en: "Aruba", fr: "Aruba" } },
  AU: { code: "AU", name: { pt: "Austrália", en: "Australia", fr: "Australie" } },
  AT: { code: "AT", name: { pt: "Áustria", en: "Austria", fr: "Autriche" } },
  AZ: { code: "AZ", name: { pt: "Azerbaijão", en: "Azerbaijan", fr: "Azerbaïdjan" } },
  BS: { code: "BS", name: { pt: "Bahamas", en: "Bahamas", fr: "Bahamas" } },
  BD: { code: "BD", name: { pt: "Bangladesh", en: "Bangladesh", fr: "Bangladesh" } },
  BB: { code: "BB", name: { pt: "Barbados", en: "Barbados", fr: "Barbade" } },
  BH: { code: "BH", name: { pt: "Barein", en: "Bahrain", fr: "Bahreïn" } },
  BE: { code: "BE", name: { pt: "Bélgica", en: "Belgium", fr: "Belgique" } },
  BZ: { code: "BZ", name: { pt: "Belize", en: "Belize", fr: "Belize" } },
  BJ: { code: "BJ", name: { pt: "Benin", en: "Benin", fr: "Bénin" } },
  BM: { code: "BM", name: { pt: "Bermudas", en: "Bermuda", fr: "Bermudes" } },
  BY: { code: "BY", name: { pt: "Bielorrússia", en: "Belarus", fr: "Biélorussie" } },
  BO: { code: "BO", name: { pt: "Bolívia", en: "Bolivia", fr: "Bolivie" } },
  BA: {
    code: "BA",
    name: { pt: "Bósnia e Herzegovina", en: "Bosnia & Herzegovina", fr: "Bosnie-Herzégovine" },
  },
  BW: { code: "BW", name: { pt: "Botsuana", en: "Botswana", fr: "Botswana" } },
  BR: { code: "BR", name: { pt: "Brasil", en: "Brazil", fr: "Brésil" } },
  BN: { code: "BN", name: { pt: "Brunei", en: "Brunei", fr: "Brunei" } },
  BG: { code: "BG", name: { pt: "Bulgária", en: "Bulgaria", fr: "Bulgarie" } },
  BF: { code: "BF", name: { pt: "Burquina Faso", en: "Burkina Faso", fr: "Burkina Faso" } },
  BI: { code: "BI", name: { pt: "Burundi", en: "Burundi", fr: "Burundi" } },
  BT: { code: "BT", name: { pt: "Butão", en: "Bhutan", fr: "Bhoutan" } },
  CV: { code: "CV", name: { pt: "Cabo Verde", en: "Cape Verde", fr: "Cap-Vert" } },
  CM: { code: "CM", name: { pt: "Camarões", en: "Cameroon", fr: "Cameroun" } },
  KH: { code: "KH", name: { pt: "Camboja", en: "Cambodia", fr: "Cambodge" } },
  CA: { code: "CA", name: { pt: "Canadá", en: "Canada", fr: "Canada" } },
  QA: { code: "QA", name: { pt: "Catar", en: "Qatar", fr: "Qatar" } },
  KZ: { code: "KZ", name: { pt: "Cazaquistão", en: "Kazakhstan", fr: "Kazakhstan" } },
  TD: { code: "TD", name: { pt: "Chade", en: "Chad", fr: "Tchad" } },
  CL: { code: "CL", name: { pt: "Chile", en: "Chile", fr: "Chili" } },
  CN: { code: "CN", name: { pt: "China", en: "China", fr: "Chine" } },
  CY: { code: "CY", name: { pt: "Chipre", en: "Cyprus", fr: "Chypre" } },
  VA: {
    code: "VA",
    name: { pt: "Cidade do Vaticano", en: "Vatican City", fr: "État de la Cité du Vatican" },
  },
  CO: { code: "CO", name: { pt: "Colômbia", en: "Colombia", fr: "Colombie" } },
  KM: { code: "KM", name: { pt: "Comores", en: "Comoros", fr: "Comores" } },
  CD: {
    code: "CD",
    name: { pt: "Congo - Kinshasa", en: "Congo - Kinshasa", fr: "Congo-Kinshasa" },
  },
  KP: { code: "KP", name: { pt: "Coreia do Norte", en: "North Korea", fr: "Corée du Nord" } },
  KR: { code: "KR", name: { pt: "Coreia do Sul", en: "South Korea", fr: "Corée du Sud" } },
  CI: { code: "CI", name: { pt: "Costa do Marfim", en: "Côte d’Ivoire", fr: "Côte d’Ivoire" } },
  CR: { code: "CR", name: { pt: "Costa Rica", en: "Costa Rica", fr: "Costa Rica" } },
  HR: { code: "HR", name: { pt: "Croácia", en: "Croatia", fr: "Croatie" } },
  CU: { code: "CU", name: { pt: "Cuba", en: "Cuba", fr: "Cuba" } },
  CW: { code: "CW", name: { pt: "Curaçao", en: "Curaçao", fr: "Curaçao" } },
  DK: { code: "DK", name: { pt: "Dinamarca", en: "Denmark", fr: "Danemark" } },
  DJ: { code: "DJ", name: { pt: "Djibuti", en: "Djibouti", fr: "Djibouti" } },
  DM: { code: "DM", name: { pt: "Dominica", en: "Dominica", fr: "Dominique" } },
  EG: { code: "EG", name: { pt: "Egito", en: "Egypt", fr: "Égypte" } },
  SV: { code: "SV", name: { pt: "El Salvador", en: "El Salvador", fr: "Salvador" } },
  AE: {
    code: "AE",
    name: { pt: "Emirados Árabes Unidos", en: "United Arab Emirates", fr: "Émirats arabes unis" },
  },
  EC: { code: "EC", name: { pt: "Equador", en: "Ecuador", fr: "Équateur" } },
  ER: { code: "ER", name: { pt: "Eritreia", en: "Eritrea", fr: "Érythrée" } },
  SK: { code: "SK", name: { pt: "Eslováquia", en: "Slovakia", fr: "Slovaquie" } },
  SI: { code: "SI", name: { pt: "Eslovênia", en: "Slovenia", fr: "Slovénie" } },
  ES: { code: "ES", name: { pt: "Espanha", en: "Spain", fr: "Espagne" } },
  SZ: { code: "SZ", name: { pt: "Essuatíni", en: "Eswatini", fr: "Eswatini" } },
  US: { code: "US", name: { pt: "Estados Unidos", en: "United States", fr: "États-Unis" } },
  EE: { code: "EE", name: { pt: "Estônia", en: "Estonia", fr: "Estonie" } },
  ET: { code: "ET", name: { pt: "Etiópia", en: "Ethiopia", fr: "Éthiopie" } },
  FJ: { code: "FJ", name: { pt: "Fiji", en: "Fiji", fr: "Fidji" } },
  PH: { code: "PH", name: { pt: "Filipinas", en: "Philippines", fr: "Philippines" } },
  FI: { code: "FI", name: { pt: "Finlândia", en: "Finland", fr: "Finlande" } },
  FR: { code: "FR", name: { pt: "França", en: "France", fr: "France" } },
  GA: { code: "GA", name: { pt: "Gabão", en: "Gabon", fr: "Gabon" } },
  GM: { code: "GM", name: { pt: "Gâmbia", en: "Gambia", fr: "Gambie" } },
  GH: { code: "GH", name: { pt: "Gana", en: "Ghana", fr: "Ghana" } },
  GE: { code: "GE", name: { pt: "Geórgia", en: "Georgia", fr: "Géorgie" } },
  GI: { code: "GI", name: { pt: "Gibraltar", en: "Gibraltar", fr: "Gibraltar" } },
  GD: { code: "GD", name: { pt: "Granada", en: "Grenada", fr: "Grenade" } },
  GR: { code: "GR", name: { pt: "Grécia", en: "Greece", fr: "Grèce" } },
  GL: { code: "GL", name: { pt: "Groenlândia", en: "Greenland", fr: "Groenland" } },
  GP: { code: "GP", name: { pt: "Guadalupe", en: "Guadeloupe", fr: "Guadeloupe" } },
  GU: { code: "GU", name: { pt: "Guam", en: "Guam", fr: "Guam" } },
  GT: { code: "GT", name: { pt: "Guatemala", en: "Guatemala", fr: "Guatemala" } },
  GG: { code: "GG", name: { pt: "Guernsey", en: "Guernsey", fr: "Guernesey" } },
  GY: { code: "GY", name: { pt: "Guiana", en: "Guyana", fr: "Guyana" } },
  GF: { code: "GF", name: { pt: "Guiana Francesa", en: "French Guiana", fr: "Guyane française" } },
  GN: { code: "GN", name: { pt: "Guiné", en: "Guinea", fr: "Guinée" } },
  GQ: {
    code: "GQ",
    name: { pt: "Guiné Equatorial", en: "Equatorial Guinea", fr: "Guinée équatoriale" },
  },
  GW: { code: "GW", name: { pt: "Guiné-Bissau", en: "Guinea-Bissau", fr: "Guinée-Bissau" } },
  HT: { code: "HT", name: { pt: "Haiti", en: "Haiti", fr: "Haïti" } },
  HN: { code: "HN", name: { pt: "Honduras", en: "Honduras", fr: "Honduras" } },
  HK: {
    code: "HK",
    name: {
      pt: "Hong Kong, RAE da China",
      en: "Hong Kong SAR China",
      fr: "R.A.S. chinoise de Hong Kong",
    },
  },
  HU: { code: "HU", name: { pt: "Hungria", en: "Hungary", fr: "Hongrie" } },
  YE: { code: "YE", name: { pt: "Iêmen", en: "Yemen", fr: "Yémen" } },
  BV: { code: "BV", name: { pt: "Ilha Bouvet", en: "Bouvet Island", fr: "Île Bouvet" } },
  CX: { code: "CX", name: { pt: "Ilha Christmas", en: "Christmas Island", fr: "Île Christmas" } },
  AC: {
    code: "AC",
    name: { pt: "Ilha de Ascensão", en: "Ascension Island", fr: "Île de l’Ascension" },
  },
  IM: { code: "IM", name: { pt: "Ilha de Man", en: "Isle of Man", fr: "Île de Man" } },
  NF: { code: "NF", name: { pt: "Ilha Norfolk", en: "Norfolk Island", fr: "Île Norfolk" } },
  AX: { code: "AX", name: { pt: "Ilhas Aland", en: "Åland Islands", fr: "Îles Åland" } },
  IC: { code: "IC", name: { pt: "Ilhas Canárias", en: "Canary Islands", fr: "Îles Canaries" } },
  KY: { code: "KY", name: { pt: "Ilhas Cayman", en: "Cayman Islands", fr: "Îles Caïmans" } },
  CC: {
    code: "CC",
    name: { pt: "Ilhas Cocos (Keeling)", en: "Cocos (Keeling) Islands", fr: "Îles Cocos" },
  },
  CK: { code: "CK", name: { pt: "Ilhas Cook", en: "Cook Islands", fr: "Îles Cook" } },
  FO: { code: "FO", name: { pt: "Ilhas Faroé", en: "Faroe Islands", fr: "Îles Féroé" } },
  GS: {
    code: "GS",
    name: {
      pt: "Ilhas Geórgia do Sul e Sandwich do Sul",
      en: "South Georgia & South Sandwich Islands",
      fr: "Géorgie du Sud-et-les Îles Sandwich du Sud",
    },
  },
  HM: {
    code: "HM",
    name: {
      pt: "Ilhas Heard e McDonald",
      en: "Heard & McDonald Islands",
      fr: "Îles Heard-et-MacDonald",
    },
  },
  FK: { code: "FK", name: { pt: "Ilhas Malvinas", en: "Falkland Islands", fr: "Îles Malouines" } },
  MP: {
    code: "MP",
    name: {
      pt: "Ilhas Marianas do Norte",
      en: "Northern Mariana Islands",
      fr: "Îles Mariannes du Nord",
    },
  },
  MH: { code: "MH", name: { pt: "Ilhas Marshall", en: "Marshall Islands", fr: "Îles Marshall" } },
  UM: {
    code: "UM",
    name: {
      pt: "Ilhas Menores Distantes dos EUA",
      en: "U.S. Outlying Islands",
      fr: "Îles mineures éloignées des États-Unis",
    },
  },
  PN: { code: "PN", name: { pt: "Ilhas Pitcairn", en: "Pitcairn Islands", fr: "Îles Pitcairn" } },
  SB: { code: "SB", name: { pt: "Ilhas Salomão", en: "Solomon Islands", fr: "Îles Salomon" } },
  TC: {
    code: "TC",
    name: {
      pt: "Ilhas Turcas e Caicos",
      en: "Turks & Caicos Islands",
      fr: "Îles Turques-et-Caïques",
    },
  },
  VI: {
    code: "VI",
    name: {
      pt: "Ilhas Virgens Americanas",
      en: "U.S. Virgin Islands",
      fr: "Îles Vierges des États-Unis",
    },
  },
  VG: {
    code: "VG",
    name: {
      pt: "Ilhas Virgens Britânicas",
      en: "British Virgin Islands",
      fr: "Îles Vierges britanniques",
    },
  },
  IN: { code: "IN", name: { pt: "Índia", en: "India", fr: "Inde" } },
  ID: { code: "ID", name: { pt: "Indonésia", en: "Indonesia", fr: "Indonésie" } },
  IR: { code: "IR", name: { pt: "Irã", en: "Iran", fr: "Iran" } },
  IQ: { code: "IQ", name: { pt: "Iraque", en: "Iraq", fr: "Irak" } },
  IE: { code: "IE", name: { pt: "Irlanda", en: "Ireland", fr: "Irlande" } },
  IS: { code: "IS", name: { pt: "Islândia", en: "Iceland", fr: "Islande" } },
  IL: { code: "IL", name: { pt: "Israel", en: "Israel", fr: "Israël" } },
  IT: { code: "IT", name: { pt: "Itália", en: "Italy", fr: "Italie" } },
  JM: { code: "JM", name: { pt: "Jamaica", en: "Jamaica", fr: "Jamaïque" } },
  JP: { code: "JP", name: { pt: "Japão", en: "Japan", fr: "Japon" } },
  JE: { code: "JE", name: { pt: "Jersey", en: "Jersey", fr: "Jersey" } },
  JO: { code: "JO", name: { pt: "Jordânia", en: "Jordan", fr: "Jordanie" } },
  XK: { code: "XK", name: { pt: "Kosovo", en: "Kosovo", fr: "Kosovo" } },
  KW: { code: "KW", name: { pt: "Kuwait", en: "Kuwait", fr: "Koweït" } },
  LA: { code: "LA", name: { pt: "Laos", en: "Laos", fr: "Laos" } },
  LS: { code: "LS", name: { pt: "Lesoto", en: "Lesotho", fr: "Lesotho" } },
  LV: { code: "LV", name: { pt: "Letônia", en: "Latvia", fr: "Lettonie" } },
  LB: { code: "LB", name: { pt: "Líbano", en: "Lebanon", fr: "Liban" } },
  LR: { code: "LR", name: { pt: "Libéria", en: "Liberia", fr: "Liberia" } },
  LY: { code: "LY", name: { pt: "Líbia", en: "Libya", fr: "Libye" } },
  LI: { code: "LI", name: { pt: "Liechtenstein", en: "Liechtenstein", fr: "Liechtenstein" } },
  LT: { code: "LT", name: { pt: "Lituânia", en: "Lithuania", fr: "Lituanie" } },
  LU: { code: "LU", name: { pt: "Luxemburgo", en: "Luxembourg", fr: "Luxembourg" } },
  MO: {
    code: "MO",
    name: { pt: "Macau, RAE da China", en: "Macao SAR China", fr: "R.A.S. chinoise de Macao" },
  },
  MK: {
    code: "MK",
    name: { pt: "Macedônia do Norte", en: "North Macedonia", fr: "Macédoine du Nord" },
  },
  MG: { code: "MG", name: { pt: "Madagascar", en: "Madagascar", fr: "Madagascar" } },
  MY: { code: "MY", name: { pt: "Malásia", en: "Malaysia", fr: "Malaisie" } },
  MW: { code: "MW", name: { pt: "Malaui", en: "Malawi", fr: "Malawi" } },
  MV: { code: "MV", name: { pt: "Maldivas", en: "Maldives", fr: "Maldives" } },
  ML: { code: "ML", name: { pt: "Mali", en: "Mali", fr: "Mali" } },
  MT: { code: "MT", name: { pt: "Malta", en: "Malta", fr: "Malte" } },
  MA: { code: "MA", name: { pt: "Marrocos", en: "Morocco", fr: "Maroc" } },
  MQ: { code: "MQ", name: { pt: "Martinica", en: "Martinique", fr: "Martinique" } },
  MU: { code: "MU", name: { pt: "Maurício", en: "Mauritius", fr: "Maurice" } },
  MR: { code: "MR", name: { pt: "Mauritânia", en: "Mauritania", fr: "Mauritanie" } },
  YT: { code: "YT", name: { pt: "Mayotte", en: "Mayotte", fr: "Mayotte" } },
  MX: { code: "MX", name: { pt: "México", en: "Mexico", fr: "Mexique" } },
  MM: {
    code: "MM",
    name: { pt: "Mianmar (Birmânia)", en: "Myanmar (Burma)", fr: "Myanmar (Birmanie)" },
  },
  FM: { code: "FM", name: { pt: "Micronésia", en: "Micronesia", fr: "Micronésie" } },
  MZ: { code: "MZ", name: { pt: "Moçambique", en: "Mozambique", fr: "Mozambique" } },
  MD: { code: "MD", name: { pt: "Moldávia", en: "Moldova", fr: "Moldavie" } },
  MC: { code: "MC", name: { pt: "Mônaco", en: "Monaco", fr: "Monaco" } },
  MN: { code: "MN", name: { pt: "Mongólia", en: "Mongolia", fr: "Mongolie" } },
  ME: { code: "ME", name: { pt: "Montenegro", en: "Montenegro", fr: "Monténégro" } },
  MS: { code: "MS", name: { pt: "Montserrat", en: "Montserrat", fr: "Montserrat" } },
  NA: { code: "NA", name: { pt: "Namíbia", en: "Namibia", fr: "Namibie" } },
  NR: { code: "NR", name: { pt: "Nauru", en: "Nauru", fr: "Nauru" } },
  NP: { code: "NP", name: { pt: "Nepal", en: "Nepal", fr: "Népal" } },
  NI: { code: "NI", name: { pt: "Nicarágua", en: "Nicaragua", fr: "Nicaragua" } },
  NE: { code: "NE", name: { pt: "Níger", en: "Niger", fr: "Niger" } },
  NG: { code: "NG", name: { pt: "Nigéria", en: "Nigeria", fr: "Nigeria" } },
  NU: { code: "NU", name: { pt: "Niue", en: "Niue", fr: "Niue" } },
  NO: { code: "NO", name: { pt: "Noruega", en: "Norway", fr: "Norvège" } },
  NC: { code: "NC", name: { pt: "Nova Caledônia", en: "New Caledonia", fr: "Nouvelle-Calédonie" } },
  NZ: { code: "NZ", name: { pt: "Nova Zelândia", en: "New Zealand", fr: "Nouvelle-Zélande" } },
  OM: { code: "OM", name: { pt: "Omã", en: "Oman", fr: "Oman" } },
  NL: { code: "NL", name: { pt: "Países Baixos", en: "Netherlands", fr: "Pays-Bas" } },
  BQ: {
    code: "BQ",
    name: { pt: "Países Baixos Caribenhos", en: "Caribbean Netherlands", fr: "Pays-Bas caribéens" },
  },
  PW: { code: "PW", name: { pt: "Palau", en: "Palau", fr: "Palaos" } },
  PA: { code: "PA", name: { pt: "Panamá", en: "Panama", fr: "Panama" } },
  PG: {
    code: "PG",
    name: { pt: "Papua-Nova Guiné", en: "Papua New Guinea", fr: "Papouasie-Nouvelle-Guinée" },
  },
  PK: { code: "PK", name: { pt: "Paquistão", en: "Pakistan", fr: "Pakistan" } },
  PY: { code: "PY", name: { pt: "Paraguai", en: "Paraguay", fr: "Paraguay" } },
  PE: { code: "PE", name: { pt: "Peru", en: "Peru", fr: "Pérou" } },
  PF: {
    code: "PF",
    name: { pt: "Polinésia Francesa", en: "French Polynesia", fr: "Polynésie française" },
  },
  PL: { code: "PL", name: { pt: "Polônia", en: "Poland", fr: "Pologne" } },
  PR: { code: "PR", name: { pt: "Porto Rico", en: "Puerto Rico", fr: "Porto Rico" } },
  PT: { code: "PT", name: { pt: "Portugal", en: "Portugal", fr: "Portugal" } },
  XA: { code: "XA", name: { pt: "Pseudossotaques", en: "Pseudo-Accents", fr: "pseudo-accents" } },
  KE: { code: "KE", name: { pt: "Quênia", en: "Kenya", fr: "Kenya" } },
  KG: { code: "KG", name: { pt: "Quirguistão", en: "Kyrgyzstan", fr: "Kirghizstan" } },
  KI: { code: "KI", name: { pt: "Quiribati", en: "Kiribati", fr: "Kiribati" } },
  GB: { code: "GB", name: { pt: "Reino Unido", en: "United Kingdom", fr: "Royaume-Uni" } },
  CF: {
    code: "CF",
    name: {
      pt: "República Centro-Africana",
      en: "Central African Republic",
      fr: "République centrafricaine",
    },
  },
  CG: {
    code: "CG",
    name: { pt: "República do Congo", en: "Congo - Brazzaville", fr: "Congo-Brazzaville" },
  },
  DO: {
    code: "DO",
    name: { pt: "República Dominicana", en: "Dominican Republic", fr: "République dominicaine" },
  },
  RE: { code: "RE", name: { pt: "Reunião", en: "Réunion", fr: "La Réunion" } },
  RO: { code: "RO", name: { pt: "Romênia", en: "Romania", fr: "Roumanie" } },
  RW: { code: "RW", name: { pt: "Ruanda", en: "Rwanda", fr: "Rwanda" } },
  RU: { code: "RU", name: { pt: "Rússia", en: "Russia", fr: "Russie" } },
  EH: {
    code: "EH",
    name: { pt: "Saara Ocidental", en: "Western Sahara", fr: "Sahara occidental" },
  },
  WS: { code: "WS", name: { pt: "Samoa", en: "Samoa", fr: "Samoa" } },
  AS: {
    code: "AS",
    name: { pt: "Samoa Americana", en: "American Samoa", fr: "Samoa américaines" },
  },
  SM: { code: "SM", name: { pt: "San Marino", en: "San Marino", fr: "Saint-Marin" } },
  SH: { code: "SH", name: { pt: "Santa Helena", en: "St. Helena", fr: "Sainte-Hélène" } },
  LC: { code: "LC", name: { pt: "Santa Lúcia", en: "St. Lucia", fr: "Sainte-Lucie" } },
  BL: { code: "BL", name: { pt: "São Bartolomeu", en: "St. Barthélemy", fr: "Saint-Barthélemy" } },
  KN: {
    code: "KN",
    name: {
      pt: "São Cristóvão e Névis",
      en: "St. Kitts & Nevis",
      fr: "Saint-Christophe-et-Niévès",
    },
  },
  MF: { code: "MF", name: { pt: "São Martinho", en: "St. Martin", fr: "Saint-Martin" } },
  PM: {
    code: "PM",
    name: {
      pt: "São Pedro e Miquelão",
      en: "St. Pierre & Miquelon",
      fr: "Saint-Pierre-et-Miquelon",
    },
  },
  ST: {
    code: "ST",
    name: { pt: "São Tomé e Príncipe", en: "São Tomé & Príncipe", fr: "Sao Tomé-et-Principe" },
  },
  VC: {
    code: "VC",
    name: {
      pt: "São Vicente e Granadinas",
      en: "St. Vincent & Grenadines",
      fr: "Saint-Vincent-et-les Grenadines",
    },
  },
  SC: { code: "SC", name: { pt: "Seicheles", en: "Seychelles", fr: "Seychelles" } },
  SN: { code: "SN", name: { pt: "Senegal", en: "Senegal", fr: "Sénégal" } },
  SL: { code: "SL", name: { pt: "Serra Leoa", en: "Sierra Leone", fr: "Sierra Leone" } },
  RS: { code: "RS", name: { pt: "Sérvia", en: "Serbia", fr: "Serbie" } },
  SG: { code: "SG", name: { pt: "Singapura", en: "Singapore", fr: "Singapour" } },
  SX: {
    code: "SX",
    name: { pt: "Sint Maarten", en: "Sint Maarten", fr: "Saint-Martin (partie néerlandaise)" },
  },
  SY: { code: "SY", name: { pt: "Síria", en: "Syria", fr: "Syrie" } },
  SO: { code: "SO", name: { pt: "Somália", en: "Somalia", fr: "Somalie" } },
  LK: { code: "LK", name: { pt: "Sri Lanka", en: "Sri Lanka", fr: "Sri Lanka" } },
  SD: { code: "SD", name: { pt: "Sudão", en: "Sudan", fr: "Soudan" } },
  SS: { code: "SS", name: { pt: "Sudão do Sul", en: "South Sudan", fr: "Soudan du Sud" } },
  SE: { code: "SE", name: { pt: "Suécia", en: "Sweden", fr: "Suède" } },
  CH: { code: "CH", name: { pt: "Suíça", en: "Switzerland", fr: "Suisse" } },
  SR: { code: "SR", name: { pt: "Suriname", en: "Suriname", fr: "Suriname" } },
  SJ: {
    code: "SJ",
    name: { pt: "Svalbard e Jan Mayen", en: "Svalbard & Jan Mayen", fr: "Svalbard et Jan Mayen" },
  },
  TJ: { code: "TJ", name: { pt: "Tadjiquistão", en: "Tajikistan", fr: "Tadjikistan" } },
  TH: { code: "TH", name: { pt: "Tailândia", en: "Thailand", fr: "Thaïlande" } },
  TW: { code: "TW", name: { pt: "Taiwan", en: "Taiwan", fr: "Taïwan" } },
  TZ: { code: "TZ", name: { pt: "Tanzânia", en: "Tanzania", fr: "Tanzanie" } },
  CZ: { code: "CZ", name: { pt: "Tchéquia", en: "Czechia", fr: "Tchéquie" } },
  IO: {
    code: "IO",
    name: {
      pt: "Território Britânico do Oceano Índico",
      en: "British Indian Ocean Territory",
      fr: "Territoire britannique de l’océan Indien",
    },
  },
  TF: {
    code: "TF",
    name: {
      pt: "Territórios Franceses do Sul",
      en: "French Southern Territories",
      fr: "Terres australes françaises",
    },
  },
  PS: {
    code: "PS",
    name: {
      pt: "Territórios palestinos",
      en: "Palestinian Territories",
      fr: "Territoires palestiniens",
    },
  },
  TL: { code: "TL", name: { pt: "Timor-Leste", en: "Timor-Leste", fr: "Timor oriental" } },
  TG: { code: "TG", name: { pt: "Togo", en: "Togo", fr: "Togo" } },
  TK: { code: "TK", name: { pt: "Tokelau", en: "Tokelau", fr: "Tokelau" } },
  TO: { code: "TO", name: { pt: "Tonga", en: "Tonga", fr: "Tonga" } },
  TT: {
    code: "TT",
    name: { pt: "Trinidad e Tobago", en: "Trinidad & Tobago", fr: "Trinité-et-Tobago" },
  },
  TA: {
    code: "TA",
    name: { pt: "Tristão da Cunha", en: "Tristan da Cunha", fr: "Tristan da Cunha" },
  },
  TN: { code: "TN", name: { pt: "Tunísia", en: "Tunisia", fr: "Tunisie" } },
  TM: { code: "TM", name: { pt: "Turcomenistão", en: "Turkmenistan", fr: "Turkménistan" } },
  TR: { code: "TR", name: { pt: "Turquia", en: "Türkiye", fr: "Turquie" } },
  TV: { code: "TV", name: { pt: "Tuvalu", en: "Tuvalu", fr: "Tuvalu" } },
  UA: { code: "UA", name: { pt: "Ucrânia", en: "Ukraine", fr: "Ukraine" } },
  UG: { code: "UG", name: { pt: "Uganda", en: "Uganda", fr: "Ouganda" } },
  EU: { code: "EU", name: { pt: "União Europeia", en: "European Union", fr: "Union européenne" } },
  UY: { code: "UY", name: { pt: "Uruguai", en: "Uruguay", fr: "Uruguay" } },
  UZ: { code: "UZ", name: { pt: "Uzbequistão", en: "Uzbekistan", fr: "Ouzbékistan" } },
  VU: { code: "VU", name: { pt: "Vanuatu", en: "Vanuatu", fr: "Vanuatu" } },
  VE: { code: "VE", name: { pt: "Venezuela", en: "Venezuela", fr: "Venezuela" } },
  VN: { code: "VN", name: { pt: "Vietnã", en: "Vietnam", fr: "Viêt Nam" } },
  WF: {
    code: "WF",
    name: { pt: "Wallis e Futuna", en: "Wallis & Futuna", fr: "Wallis-et-Futuna" },
  },
  ZM: { code: "ZM", name: { pt: "Zâmbia", en: "Zambia", fr: "Zambie" } },
  ZW: { code: "ZW", name: { pt: "Zimbábue", en: "Zimbabwe", fr: "Zimbabwe" } },
};

/** Every country code, sorted by Portuguese name. */
export const COUNTRY_ORDER: CountryCode[] = [
  "AF",
  "ZA",
  "AL",
  "DE",
  "AD",
  "AO",
  "AI",
  "AQ",
  "AG",
  "SA",
  "DZ",
  "AR",
  "AM",
  "AW",
  "AU",
  "AT",
  "AZ",
  "BS",
  "BD",
  "BB",
  "BH",
  "BE",
  "BZ",
  "BJ",
  "BM",
  "BY",
  "BO",
  "BA",
  "BW",
  "BR",
  "BN",
  "BG",
  "BF",
  "BI",
  "BT",
  "CV",
  "CM",
  "KH",
  "CA",
  "QA",
  "KZ",
  "TD",
  "CL",
  "CN",
  "CY",
  "VA",
  "CO",
  "KM",
  "CD",
  "KP",
  "KR",
  "CI",
  "CR",
  "HR",
  "CU",
  "CW",
  "DK",
  "DJ",
  "DM",
  "EG",
  "SV",
  "AE",
  "EC",
  "ER",
  "SK",
  "SI",
  "ES",
  "SZ",
  "US",
  "EE",
  "ET",
  "FJ",
  "PH",
  "FI",
  "FR",
  "GA",
  "GM",
  "GH",
  "GE",
  "GI",
  "GD",
  "GR",
  "GL",
  "GP",
  "GU",
  "GT",
  "GG",
  "GY",
  "GF",
  "GN",
  "GQ",
  "GW",
  "HT",
  "HN",
  "HK",
  "HU",
  "YE",
  "BV",
  "CX",
  "AC",
  "IM",
  "NF",
  "AX",
  "IC",
  "KY",
  "CC",
  "CK",
  "FO",
  "GS",
  "HM",
  "FK",
  "MP",
  "MH",
  "UM",
  "PN",
  "SB",
  "TC",
  "VI",
  "VG",
  "IN",
  "ID",
  "IR",
  "IQ",
  "IE",
  "IS",
  "IL",
  "IT",
  "JM",
  "JP",
  "JE",
  "JO",
  "XK",
  "KW",
  "LA",
  "LS",
  "LV",
  "LB",
  "LR",
  "LY",
  "LI",
  "LT",
  "LU",
  "MO",
  "MK",
  "MG",
  "MY",
  "MW",
  "MV",
  "ML",
  "MT",
  "MA",
  "MQ",
  "MU",
  "MR",
  "YT",
  "MX",
  "MM",
  "FM",
  "MZ",
  "MD",
  "MC",
  "MN",
  "ME",
  "MS",
  "NA",
  "NR",
  "NP",
  "NI",
  "NE",
  "NG",
  "NU",
  "NO",
  "NC",
  "NZ",
  "OM",
  "NL",
  "BQ",
  "PW",
  "PA",
  "PG",
  "PK",
  "PY",
  "PE",
  "PF",
  "PL",
  "PR",
  "PT",
  "XA",
  "KE",
  "KG",
  "KI",
  "GB",
  "CF",
  "CG",
  "DO",
  "RE",
  "RO",
  "RW",
  "RU",
  "EH",
  "WS",
  "AS",
  "SM",
  "SH",
  "LC",
  "BL",
  "KN",
  "MF",
  "PM",
  "ST",
  "VC",
  "SC",
  "SN",
  "SL",
  "RS",
  "SG",
  "SX",
  "SY",
  "SO",
  "LK",
  "SD",
  "SS",
  "SE",
  "CH",
  "SR",
  "SJ",
  "TJ",
  "TH",
  "TW",
  "TZ",
  "CZ",
  "IO",
  "TF",
  "PS",
  "TL",
  "TG",
  "TK",
  "TO",
  "TT",
  "TA",
  "TN",
  "TM",
  "TR",
  "TV",
  "UA",
  "UG",
  "EU",
  "UY",
  "UZ",
  "VU",
  "VE",
  "VN",
  "WF",
  "ZM",
  "ZW",
];

export const BR_STATES: Record<string, BrStateMeta> = {
  AC: { code: "AC", name: "Acre", region: "Norte" },
  AL: { code: "AL", name: "Alagoas", region: "Nordeste" },
  AP: { code: "AP", name: "Amapá", region: "Norte" },
  AM: { code: "AM", name: "Amazonas", region: "Norte" },
  BA: { code: "BA", name: "Bahia", region: "Nordeste" },
  CE: { code: "CE", name: "Ceará", region: "Nordeste" },
  DF: { code: "DF", name: "Distrito Federal", region: "Centro-Oeste" },
  ES: { code: "ES", name: "Espírito Santo", region: "Sudeste" },
  GO: { code: "GO", name: "Goiás", region: "Centro-Oeste" },
  MA: { code: "MA", name: "Maranhão", region: "Nordeste" },
  MT: { code: "MT", name: "Mato Grosso", region: "Centro-Oeste" },
  MS: { code: "MS", name: "Mato Grosso do Sul", region: "Centro-Oeste" },
  MG: { code: "MG", name: "Minas Gerais", region: "Sudeste" },
  PA: { code: "PA", name: "Pará", region: "Norte" },
  PB: { code: "PB", name: "Paraíba", region: "Nordeste" },
  PR: { code: "PR", name: "Paraná", region: "Sul" },
  PE: { code: "PE", name: "Pernambuco", region: "Nordeste" },
  PI: { code: "PI", name: "Piauí", region: "Nordeste" },
  RJ: { code: "RJ", name: "Rio de Janeiro", region: "Sudeste" },
  RN: { code: "RN", name: "Rio Grande do Norte", region: "Nordeste" },
  RS: { code: "RS", name: "Rio Grande do Sul", region: "Sul" },
  RO: { code: "RO", name: "Rondônia", region: "Norte" },
  RR: { code: "RR", name: "Roraima", region: "Norte" },
  SC: { code: "SC", name: "Santa Catarina", region: "Sul" },
  SP: { code: "SP", name: "São Paulo", region: "Sudeste" },
  SE: { code: "SE", name: "Sergipe", region: "Nordeste" },
  TO: { code: "TO", name: "Tocantins", region: "Norte" },
};

/** UFs in alphabetical order. */
export const BR_STATE_ORDER: string[] = [
  "AC",
  "AL",
  "AP",
  "AM",
  "BA",
  "CE",
  "DF",
  "ES",
  "GO",
  "MA",
  "MT",
  "MS",
  "MG",
  "PA",
  "PB",
  "PR",
  "PE",
  "PI",
  "RJ",
  "RN",
  "RS",
  "RO",
  "RR",
  "SC",
  "SP",
  "SE",
  "TO",
];

/**
 * Country name in the requested language, falling back to the raw code.
 *
 * Members carry whatever code was stored when they were edited, so a lookup can
 * miss if a code is ever retired upstream — showing "ZZ" beats rendering
 * "undefined" on the public site.
 */
export function countryName(code: string | null | undefined, lang: "pt" | "en" | "fr"): string {
  if (!code) return "";
  return COUNTRIES[code]?.name[lang] ?? code;
}

/** State name for a UF, falling back to the raw code. */
export function brStateName(code: string | null | undefined): string {
  if (!code) return "";
  return BR_STATES[code]?.name ?? code;
}
